ARG NODE_BUILD_IMAGE=node:16.20.1-bullseye
FROM $NODE_BUILD_IMAGE AS build

WORKDIR /my-cool-app
COPY . .

RUN npm clean-install
ARG TARGETOS
ARG TARGETARCH
RUN mkdir -p /out && cp /my-cool-app/build/Release/addon.node /out/addon-$TARGETOS-$TARGETARCH-glibc.node

FROM scratch

COPY --from=build /out /
