name: Setup
description: 'Installs node, driver dependencies, and builds source'

inputs:
  releasePr:
     description: 'Enter release PR number'
     required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        ref: refs/pull/${{ inputs.releasePr }}/head

    - name: actions/setup
      uses: ./.github/actions/setup

    # See: https://github.com/googleapis/release-please/issues/1274

    # Get the PRs that are in this release
    # Outputs a list of comma separated PR numbers, parsed from HISTORY.md
    - id: pr_list
      shell: bash
      run: node .github/scripts/pr_list.mjs
      env:
        GITHUB_TOKEN: ${{ github.token }}

    # From the list of PRs, gather the highlight sections of the PR body
    # output JSON with "highlights" key (to preserve newlines)
    - id: highlights
      shell: bash
      run: node .github/scripts/highlights.mjs
      env:
        GITHUB_TOKEN: ${{ github.token }}
        PR_LIST: ${{ steps.pr_list.outputs.pr_list }}

    # The combined output is available
    - id: release_notes
      shell: bash
      run: node .github/scripts/release_notes.mjs
      env:
        GITHUB_TOKEN: ${{ github.token }}
        HIGHLIGHTS: ${{ steps.highlights.outputs.highlights }}

    # Update the release PR body
    - run: gh pr edit ${{ inputs.releasePr }} --body-file ${{ steps.release_notes.outputs.release_notes_path }}
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
