on:
  issue_comment:
    types: [created]
  workflow_dispatch:
    inputs:
      releasePr:
        description: 'Enter release PR number'
        required: true
        type: number

name: release_notes

permissions:
  contents: write
  pull-requests: write

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment

    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          EVENT: ${{ toJson(github) }}
        run: |
          echo $EVENT
          exit 1

      - uses: actions/checkout@v3

      - id: checkIfAllowed
        env:
          GH_TOKEN: ${{ github.token }}
          COMMENTER: ${{ github.triggering_actor }}
        shell: bash
        run: |
          set -o pipefail
          gh api \
            "/repos/${{ github.repository }}/collaborators?per_page=100&permission=admin" --paginate --jq ".[].login" \
            | grep -q "$COMMENTER"

          exit_status=$?
          if [ -n "$exit_signal" ]; then
            echo "$COMMENTER not permitted to trigger notes"
            exit 1
          else
            echo "$COMMENTER permitted to trigger notes!"
            exit 0
          fi

      - if: ${{ github.event.comment.body == '/take-notes' }}
        name: actions/release_notes
        uses: ./.github/actions/release_notes
        with:
          releasePr: ${{ github.event.issue.number }}
