on:
  issue_comment:
    types: [created]

name: release_notes

jobs:
  pr_commented:
    # This job only runs for pull request comments
    name: PR comment
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - if: ${{ github.event.comment.body == '/take-notes' }}
        name: actions/release_notes
        uses: ./.github/actions/release_notes
        with:
          releasePr: ${{ github.event.issue.number }}
